
# test executable filename.
BIN=slice

# source filenames.
SRC=slice.c

# output data filenames.
DAT=  vfr-mean.dat vfr-var.dat vfr.p0.dat vfr.p1.dat
DAT+= gp-mean.dat gp-var.dat gp.p0.dat gp.p1.dat

# include the base testing makefile.
include ../tests.mk

