
# BIN: test executable filename.
BIN=slice

# SRC: source filenames.
SRC=main.c

# DAT: output data filenames.
DAT=mean.dat var.dat map.dat

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=775

# include the testing base makefile.
include ../tests.mk

