
# BIN: test executable filename.
BIN=linear

# SRC: source filenames.
SRC=linear.c

# DAT: output data filenames.
DAT=

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=7321

# include the testing base makefile.
include ../tests.mk

