
# test executable filename.
BIN=linear

# source filenames.
SRC=linear.c

# environment variables to set during testing.
TESTFLAGS=RNG_SEED=7321

# include the base testing makefile.
include ../tests.mk

