
# BIN: test executable filename.
BIN=toy2d

# SRC: source filenames.
SRC=toy2d.c

# DAT: output data filenames.
DAT=fit-mean.dat fit-var.dat mean.dat var.dat

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=775

# include the testing base makefile.
include ../tests.mk

