
# test executable filename.
BIN=toy2d

# source filenames.
SRC=toy2d.c

# output data filenames.
DAT=fit-mean.dat fit-var.dat mean.dat var.dat

# include the base testing makefile.
include ../tests.mk

