
# BIN: test executable filename.
BIN=toy1d

# SRC: source filenames.
SRC=main.c

# DAT: output data filenames.
DAT=meas.dat mean.dat var.dat map.dat

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=7321

# include the testing base makefile.
include ../tests.mk

