
# BIN: test executable filename.
BIN=ans1d

# SRC: source filenames.
SRC=ans1d.c

# DAT: output data filenames.
DAT=source.dat parms.dat meas*.dat vfr*.dat gp*.dat new*.dat

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=775

# include the testing base makefile.
include ../tests.mk

