
# test executable filename.
BIN=ans1d

# source filenames.
SRC=ans1d.c

# output data filenames.
DAT=source.dat parms.dat meas*.dat vfr*.dat gp*.dat new*.dat

# environment variables to set during testing.
TESTFLAGS=RNG_SEED=775

# include the base testing makefile.
include ../tests.mk

