
# test executable filename.
BIN=proton

# source filenames.
SRC=

# output data filenames.
DAT=vfr-mean.dat vfr-var.dat vfr.p0.dat vfr.p1.dat

# include the base testing makefile.
include ../tests.mk

