
# BIN: test executable filename.
BIN=slice

# SRC: source filenames.
SRC=slice.c

# DAT: output data filenames.
DAT=  vfr-mean.dat vfr-var.dat vfr.p0.dat vfr.p1.dat
DAT+= gp-mean.dat gp-var.dat gp.p0.dat gp.p1.dat

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=775

# include the testing base makefile.
include ../tests.mk

